### ISSUE TITLE
After Installation section of README

### ISSUE THREAD

**Issue by icculp** [BlockchainCommons/Bitcoin-Standup-Scripts#23]
In addition to adding a comment to address Issue #22, as well as fixing links in PR #21, the four files mentioned in the After Installation section are not consistent in either StandUp.sh or LinodeStandUp.sh. With both, the standup.log and standup.err were placed in /root/standup.log /root/standup.err rather than /standup.log and /standup.err as stated; with LinodeStandUp.sh the /qrcode.png was found in / as mentioned, but qrcode.png was not found in / or /root or ~/ with StandUp.sh. /btcstandup.uri was not found anywhere after running either script.

**Comment by icculp** [comment]
Can add to the end of both scripts to create /standup.uri:

echo $QR | sudo tee -a /standup.uri

**Comment by icculp** [comment]
In StandUp.sh add the following to create /qrcode.png, and in LinodeStandUp.sh add a / before qrcode.png to create it in the / dir to be consistent with README

# Get software packages for encoding a QR code and displaying it in a terminal
sudo apt-get install qrencode -y

# Create the QR
sudo qrencode -m 10 -o /qrcode.png "$QR"

**Comment by icculp** [comment]
In order to be consistent with https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line chapter 2.1 will need to be updated to show logs in /... instead of ~root/... (which would be /home/root...)

**Comment by icculp** [comment]
I modified the word_counter.ipynb to search for standup.log, standup.err, qrcode.png and standup.uri in the cli tutorial, and found logs in chapter 2.1, qrcode.png in chapters A1.0 and 14.1. Chapter 2 needs to be updated for logs, A1.0 and 14.1 show /...

**Comment by ChristopherA** [comment]
@icculp Are you still adding to this PR? When you are ready tag @shannona for a final review. And if you think there need to be fixes in the LBtcftCL repo we welcome PR or suggestions.

**Comment by icculp** [comment]
I am done with my changes, and I have issued a PR for the other repo as well https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/pull/275
@shannona could you review please? Probably best to review both at the same time to ensure consistency
