### ISSUE TITLE
SIG VERIFICATION ERROR

### ISSUE THREAD

**Issue by BuildWithData** [BlockchainCommons/Bitcoin-Standup-Scripts#44]
### **Scenario**

I have been following the [instructions](https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/02_1_Setting_Up_a_Bitcoin-Core_VPS_with_StackScript.md) to spin a bitcoin vps and used the standup script available in this repo. When I tried to verify the bitcoin setup by typing:

    $ sudo grep VERIFICATION /standup.log

I got this ouput:

    ./standup.sh - SIG VERIFICATION ERROR: No verified signatures for Bitcoin!

so the signature verification fails

### **Problem**

This simply happens because the [URL](https://raw.githubusercontent.com/bitcoin/bitcoin/master/contrib/builder-keys/keys.txt) provided in the standup script it outdated, just give it a try and you will get 404 error

So why is that ? I did not find any explanation, however @achow101 wrote [here](https://bitcointalk.org/index.php?topic=5433619.msg61568660#msg61568660) that in future releases keys will be made available in [this](https://github.com/bitcoin-core/guix.sigs) separate repo

### **Solution**

As long as the standup script features bitcoin core 23.0, keys can be found [here](https://raw.githubusercontent.com/bitcoin/bitcoin/23.x/contrib/builder-keys/keys.txt), but it might be worth thinking how to get the keys from the repo mentioned by @achow101

Hope this helps, let me know If you want me to open a pull request to patch the code :) 

thanks a lot for these fantastic repos !!!

**Comment by shannona** [comment]
A patch would be terrific, @BuildWithData . If you send it through and give me a ping here, I'll do some testing so that we can release.

**Comment by BuildWithData** [comment]
thanks for the reply @shannona, opened a pull request [here](https://github.com/BlockchainCommons/Bitcoin-Standup-Scripts/pull/45)

**Comment by shannona** [comment]
Thank you, @BuildWithData , tested and merged!

Feel like doing anything more? If so it'd be lovely to get this updated to Bitcoin 25 (which just requires updating the version number and presumably your new signatures link, and then testing it and *hopefully* having it work) and also to test it out on Debian 12.

(If not, thank you very much for this fix!)

**Comment by BuildWithData** [comment]
@shannona sure, I'll give it a try this weekend and open a pull request as soon as I get it working

**Comment by BuildWithData** [comment]
@shannona sure, I'll give it a try this weekend and open a pull request as soon as I get it working

**Comment by shannona** [comment]
Terrific! Looking forward to it!
